In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("onlinefoods.csv")

In [3]:
data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes
3,22,Female,Single,Student,No Income,Graduate,6,12.9473,77.5616,560019,Yes,Positive,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,12.9850,77.5533,560010,Yes,Positive,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,12.9766,77.5993,560001,Yes,Positive,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,12.9854,77.7081,560048,Yes,Positive,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,12.9850,77.5533,560010,Yes,Positive,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,12.9770,77.5773,560009,Yes,Positive,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,12.8988,77.5764,560078,Yes,Positive,Yes

In [4]:
type(data["latitude"][1])

numpy.float64

In [5]:
data.head(3)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,12.9770,77.5773,560009,Yes,Positive,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,12.9551,77.6593,560017,Yes,Negative,Yes

In [6]:
data.shape

(388, 13)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         388 non-null    int64
 1   Gender                      388 non-null    object
 2   Marital Status              388 non-null    object
 3   Occupation                  388 non-null    object
 4   Monthly Income              388 non-null    object
 5   Educational Qualifications  388 non-null    object
 6   Family size                 388 non-null    int64
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64
 10  Output                      388 non-null    object
 11  Feedback                    388 non-null    object
 12  Unnamed: 12                 388 non-null    object
dtypes: float64(2), int64(3), object(8)
memory usage: 39.5+ KB

In [8]:
data.head(1)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,latitude,longitude,Pin code,Output,Feedback,Unnamed: 12
0,20,Female,Single,Student,No Income,Post Graduate,4,12.9766,77.5993,560001,Yes,Positive,Yes

In [22]:
data.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

In [23]:
columns_to_keep = ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size','Pin code','Output']
columns_to_drop = ['latitude', 'longitude','Feedback', 'Unnamed: 12']

In [24]:
len(columns_to_keep)

9

In [29]:
len(columns_to_drop)

4

In [32]:
modify_data = data[columns_to_keep]

In [33]:
modify_data

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Pin code,Output
0,20,Female,Single,Student,No Income,Post Graduate,4,560001,Yes
1,24,Female,Single,Student,Below Rs.10000,Graduate,3,560009,Yes
2,22,Male,Single,Student,Below Rs.10000,Post Graduate,3,560017,Yes
3,22,Female,Single,Student,No Income,Graduate,6,560019,Yes
4,22,Male,Single,Student,Below Rs.10000,Post Graduate,4,560010,Yes
...,...,...,...,...,...,...,...,...,...
383,23,Female,Single,Student,No Income,Post Graduate,2,560001,Yes
384,23,Female,Single,Student,No Income,Post Graduate,4,560048,Yes
385,22,Female,Single,Student,No Income,Post Graduate,5,560010,Yes
386,23,Male,Single,Student,Below Rs.10000,Post Graduate,2,560009,Yes
387,23,Male,Single,Student,No Income,Post Graduate,5,560078,Yes

In [34]:
data.drop(columns=columns_to_drop, inplace=True)

In [36]:
data.head(1)

,Age,Gender,Marital Status,Occupation,Monthly Income,Educational Qualifications,Family size,Pin code,Output
0,20,Female,Single,Student,No Income,Post Graduate,4,560001,Yes

In [37]:
data.rename(columns = {"Monthly Income" : "Monthly Salary"},inplace=True)

In [38]:
data.head(1)

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output
0,20,Female,Single,Student,No Income,Post Graduate,4,560001,Yes

In [43]:
data.duplicated().sum()

np.int64(108)

In [44]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Salary                0
Educational Qualifications    0
Family size                   0
Pin code                      0
Output                        0
dtype: int64

In [45]:
data.dropna(inplace =True)

In [46]:
data.isna().sum()

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Salary                0
Educational Qualifications    0
Family size                   0
Pin code                      0
Output                        0
dtype: int64

In [48]:
data["Age (Month)"] = data["Age"]

In [49]:
data.head(1)

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,Female,Single,Student,No Income,Post Graduate,4,560001,Yes,20

In [53]:
data["Gender"] = data["Gender"].apply(lambda x : "F" if x == "Female" else "M")

In [56]:
data["Family size"] = data["Family size"].apply(lambda x:"Large" if x>3 else "Small" )

In [57]:
data

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,F,Single,Student,No Income,Post Graduate,Large,560001,Yes,20
1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,Yes,24
2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,Yes,22
3,22,F,Single,Student,No Income,Graduate,Large,560019,Yes,22
4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,Yes,22
...,...,...,...,...,...,...,...,...,...,...
383,23,F,Single,Student,No Income,Post Graduate,Small,560001,Yes,23
384,23,F,Single,Student,No Income,Post Graduate,Large,560048,Yes,23
385,22,F,Single,Student,No Income,Post Graduate,Large,560010,Yes,22
386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,Yes,23
387,23,M,Single,Student,No Income,Post Graduate,Large,560078,Yes,23

In [58]:
data["Output"] = data["Output"].apply(lambda x:1 if x == "Yes" else 0)

In [59]:
data

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,F,Single,Student,No Income,Post Graduate,Large,560001,1,20
1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,1,24
2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,1,22
3,22,F,Single,Student,No Income,Graduate,Large,560019,1,22
4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,1,22
...,...,...,...,...,...,...,...,...,...,...
383,23,F,Single,Student,No Income,Post Graduate,Small,560001,1,23
384,23,F,Single,Student,No Income,Post Graduate,Large,560048,1,23
385,22,F,Single,Student,No Income,Post Graduate,Large,560010,1,22
386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,1,23
387,23,M,Single,Student,No Income,Post Graduate,Large,560078,1,23

In [61]:
data["Output"] = data["Output"].astype(float)

In [62]:
data

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,F,Single,Student,No Income,Post Graduate,Large,560001,1.0,20
1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,1.0,24
2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,1.0,22
3,22,F,Single,Student,No Income,Graduate,Large,560019,1.0,22
4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,1.0,22
...,...,...,...,...,...,...,...,...,...,...
383,23,F,Single,Student,No Income,Post Graduate,Small,560001,1.0,23
384,23,F,Single,Student,No Income,Post Graduate,Large,560048,1.0,23
385,22,F,Single,Student,No Income,Post Graduate,Large,560010,1.0,22
386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,1.0,23
387,23,M,Single,Student,No Income,Post Graduate,Large,560078,1.0,23

In [63]:
data.to_excel("claened_data.xlsx", index= False)

In [64]:
data.to_csv("cleaned_csv.csv")

In [65]:
pd.read_excel("claened_data.xlsx")

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,F,Single,Student,No Income,Post Graduate,Large,560001,1,20
1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,1,24
2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,1,22
3,22,F,Single,Student,No Income,Graduate,Large,560019,1,22
4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,1,22
...,...,...,...,...,...,...,...,...,...,...
383,23,F,Single,Student,No Income,Post Graduate,Small,560001,1,23
384,23,F,Single,Student,No Income,Post Graduate,Large,560048,1,23
385,22,F,Single,Student,No Income,Post Graduate,Large,560010,1,22
386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,1,23
387,23,M,Single,Student,No Income,Post Graduate,Large,560078,1,23

In [66]:
pd.read_csv("cleaned_csv.csv")

,Unnamed: 0,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,0,20,F,Single,Student,No Income,Post Graduate,Large,560001,1.0,20
1,1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,1.0,24
2,2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,1.0,22
3,3,22,F,Single,Student,No Income,Graduate,Large,560019,1.0,22
4,4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,1.0,22
...,...,...,...,...,...,...,...,...,...,...,...
383,383,23,F,Single,Student,No Income,Post Graduate,Small,560001,1.0,23
384,384,23,F,Single,Student,No Income,Post Graduate,Large,560048,1.0,23
385,385,22,F,Single,Student,No Income,Post Graduate,Large,560010,1.0,22
386,386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,1.0,23
387,387,23,M,Single,Student,No Income,Post Graduate,Large,560078,1.0,23

In [67]:
data.to_json("cleaned_json.json")

In [68]:
pd.read_json("cleaned_json.json")

,Age,Gender,Marital Status,Occupation,Monthly Salary,Educational Qualifications,Family size,Pin code,Output,Age (Month)
0,20,F,Single,Student,No Income,Post Graduate,Large,560001,1,20
1,24,F,Single,Student,Below Rs.10000,Graduate,Small,560009,1,24
2,22,M,Single,Student,Below Rs.10000,Post Graduate,Small,560017,1,22
3,22,F,Single,Student,No Income,Graduate,Large,560019,1,22
4,22,M,Single,Student,Below Rs.10000,Post Graduate,Large,560010,1,22
...,...,...,...,...,...,...,...,...,...,...
383,23,F,Single,Student,No Income,Post Graduate,Small,560001,1,23
384,23,F,Single,Student,No Income,Post Graduate,Large,560048,1,23
385,22,F,Single,Student,No Income,Post Graduate,Large,560010,1,22
386,23,M,Single,Student,Below Rs.10000,Post Graduate,Small,560009,1,23
387,23,M,Single,Student,No Income,Post Graduate,Large,560078,1,23